# Generated by Django 5.2.5 on 2026-08-29 06:53

import community.models
import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('community', '0002_communityrequest_privatemessage'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ResidenceCertificateRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('applicant_name', models.CharField(max_length=180)),
                ('rut', models.CharField(max_length=12)),
                ('address', models.CharField(max_length=250)),
                ('commune', models.CharField(max_length=120)),
                ('purpose', models.CharField(max_length=250)),
                ('proof_type', models.CharField(choices=[('utility_bill', 'Cuenta de servicio básico'), ('lease', 'Contrato de arriendo'), ('bank_statement', 'Documento bancario o institucional'), ('other', 'Otro comprobante')], max_length=30)),
                ('proof_document', models.FileField(upload_to=community.models.residence_proof_upload)),
                ('document_date', models.DateField()),
                ('proof_sha256', models.CharField(editable=False, max_length=64)),
                ('sworn_declaration', models.BooleanField(default=False)),
                ('automatic_status', models.CharField(choices=[('passed', 'Prevalidación aprobada'), ('review', 'Revisión manual necesaria')], default='review', max_length=20)),
                ('automatic_notes', models.TextField(blank=True)),
                ('status', models.CharField(choices=[('pending', 'Pendiente de revisión'), ('needs_changes', 'Requiere corrección'), ('rejected', 'Rechazada'), ('issued', 'Certificado emitido')], default='pending', max_length=20)),
                ('reviewer_notes', models.TextField(blank=True)),
                ('reviewed_at', models.DateTimeField(blank=True, null=True)),
                ('certificate_number', models.CharField(blank=True, max_length=30, null=True, unique=True)),
                ('verification_code', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('issued_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('neighborhood', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='residence_certificate_requests', to='community.neighborhood')),
                ('requester', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='residence_certificate_requests', to=settings.AUTH_USER_MODEL)),
                ('reviewed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reviewed_residence_certificates', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
