import {FormEvent,useCallback,useEffect,useState} from 'react';
import {BarChart3,Bot,Building2,CalendarDays,ClipboardList,FileText,Home,LogOut,Mail,Megaphone,ShieldCheck,Trash2,Users} from 'lucide-react';
import {api,login,token} from './api';
import {MessagesView,OrganizationView,RequestsView} from './modules';

type View='home'|'posts'|'activities'|'documents'|'messages'|'requests'|'organization'|'indicators'|'assistant'|'neighbors';
type Me={id:number;username:string;first_name:string;role:string};
type Dashboard={neighbors:number;posts:number;activities:number;documents:number;average_age:number;older_adults:number;age_groups:{children:number;adults:number;older:number}};
type Post={id:number;title:string;content:string;created_at:string};
type ActivityItem={id:number;title:string;description:string;starts_at:string;location:string};
type DocumentItem={id:number;title:string;category:string;url:string;created_at:string};
type Profile={id:number;username:string;first_name:string;last_name:string;email:string;role:string;birth_year:number|null;household_size:number};

function Login({done}:{done:()=>void}){const[u,setU]=useState('directiva'),[p,setP]=useState('Demo1234!'),[error,setError]=useState('');async function submit(e:FormEvent){e.preventDefault();try{await login(u,p);done()}catch(x){setError((x as Error).message)}}return <main className="login"><section className="login-card"><div className="brand"><span>Comunidad</span><strong>Inteligente</strong></div><h1>Conectar personas.<br/>Comprender el territorio.</h1><p>Gestionar la junta de vecinos desde un solo lugar.</p><form onSubmit={submit}><label>Usuario<input value={u} onChange={e=>setU(e.target.value)}/></label><label>Contraseña<input type="password" value={p} onChange={e=>setP(e.target.value)}/></label>{error&&<small>{error}</small>}<button>Ingresar</button></form></section><section className="login-visual"><div className="orb"><Users size={76}/></div><h2>Gestión comunitaria + datos + IA</h2></section></main>}

const nav:Array<[View,string,typeof Home]>=[['home','Inicio',Home],['posts','Publicaciones',Megaphone],['activities','Actividades',CalendarDays],['documents','Documentos',FileText],['messages','Mensajes',Mail],['requests','Solicitudes',ClipboardList],['organization','Organización',Building2],['indicators','Indicadores',BarChart3],['assistant','Asistente IA',Bot],['neighbors','Administración',ShieldCheck]];

export default function App(){const[auth,setAuth]=useState(!!token()),[view,setView]=useState<View>('home'),[me,setMe]=useState<Me|null>(null),[dashboard,setDashboard]=useState<Dashboard|null>(null);const load=useCallback(()=>{api<Me>('/me/').then(setMe);api<Dashboard>('/dashboard/').then(setDashboard)},[]);useEffect(()=>{if(auth)load()},[auth,load]);if(!auth)return <Login done={()=>setAuth(true)}/>;return <div className="shell"><aside><div className="brand"><span>Comunidad</span><strong>Inteligente</strong></div><nav>{nav.map(([id,label,Icon])=><button key={id} className={view===id?'active':''} onClick={()=>setView(id)}><Icon/>{label}</button>)}</nav><button className="logout" onClick={()=>{localStorage.clear();setAuth(false)}}><LogOut/>Cerrar sesión</button></aside><main className="content"><header><div><p>Junta de Vecinos Nueva Esperanza</p><h1>{nav.find(n=>n[0]===view)?.[1]}</h1></div><span className="role">{me?.role==='neighbor'?'Vecino':me?.role==='admin'?'Administrador':'Directiva'} · {me?.first_name||me?.username}</span></header>{view==='home'&&<HomeView d={dashboard}/>} {view==='posts'&&<Posts canEdit={me?.role!=='neighbor'} changed={load}/>} {view==='activities'&&<Activities canEdit={me?.role!=='neighbor'} changed={load}/>} {view==='documents'&&<Documents canEdit={me?.role!=='neighbor'} changed={load}/>} {view==='messages'&&<MessagesView/>} {view==='requests'&&<RequestsView canManage={me?.role!=='neighbor'}/>} {view==='organization'&&<OrganizationView/>} {view==='indicators'&&<Indicators d={dashboard}/>} {view==='assistant'&&<Assistant/>} {view==='neighbors'&&(me?.role==='neighbor'?<Empty title="Acceso restringido" text="Esta sección está disponible para la directiva."/>:<Neighbors changed={load}/>)}</main></div>}

function HomeView({d}:{d:Dashboard|null}){const cards=[['Vecinos',d?.neighbors,Users],['Publicaciones',d?.posts,Megaphone],['Actividades',d?.activities,CalendarDays],['Documentos',d?.documents,FileText]];return <><section className="hero"><div><span>COMUNIDAD CONECTADA</span><h2>Gestionar mejor para participar más.</h2><p>Centralizar información, comunicar actividades y comprender las necesidades del territorio.</p></div><Users size={72}/></section><section className="metrics">{cards.map(([l,v,I])=>{const Icon=I as typeof Users;return <article key={l as string}><Icon/><div><strong>{v as number??'—'}</strong><span>{l as string}</span></div></article>})}</section><section className="welcome panel"><h3>Plataforma comunitaria</h3><p>Utilizar el menú para gestionar publicaciones, actividades, documentos, indicadores y vecinos. El asistente responde utilizando información autorizada del sistema.</p></section></>}

function Posts({canEdit,changed}:{canEdit:boolean;changed:()=>void}){const[items,setItems]=useState<Post[]>([]),[title,setTitle]=useState(''),[content,setContent]=useState('');const load=()=>api<Post[]>('/posts/').then(setItems);useEffect(()=>{void load()},[]);async function add(e:FormEvent){e.preventDefault();await api('/posts/',{method:'POST',body:JSON.stringify({title,content,is_published:true})});setTitle('');setContent('');load();changed()}async function del(id:number){await api(`/posts/${id}/`,{method:'DELETE'});load();changed()}return <Page title="Comunicar novedades" subtitle="Publicar información oficial para la comunidad.">{canEdit&&<form className="editor" onSubmit={add}><input required placeholder="Título de la publicación" value={title} onChange={e=>setTitle(e.target.value)}/><textarea required placeholder="Contenido" value={content} onChange={e=>setContent(e.target.value)}/><button>Publicar</button></form>}<div className="list">{items.map(x=><article key={x.id}><div><h3>{x.title}</h3><p>{x.content}</p><small>{new Date(x.created_at).toLocaleDateString('es-CL')}</small></div>{canEdit&&<button className="danger" onClick={()=>del(x.id)}><Trash2/></button>}</article>)}</div></Page>}

function Activities({canEdit,changed}:{canEdit:boolean;changed:()=>void}){const[items,setItems]=useState<ActivityItem[]>([]),[form,setForm]=useState({title:'',description:'',starts_at:'',location:''});const load=()=>api<ActivityItem[]>('/activities/').then(setItems);useEffect(()=>{void load()},[]);async function add(e:FormEvent){e.preventDefault();await api('/activities/',{method:'POST',body:JSON.stringify(form)});setForm({title:'',description:'',starts_at:'',location:''});load();changed()}async function del(id:number){await api(`/activities/${id}/`,{method:'DELETE'});load();changed()}return <Page title="Organizar actividades" subtitle="Coordinar encuentros, operativos y reuniones.">{canEdit&&<form className="editor two" onSubmit={add}><input required placeholder="Nombre" value={form.title} onChange={e=>setForm({...form,title:e.target.value})}/><input required type="datetime-local" value={form.starts_at} onChange={e=>setForm({...form,starts_at:e.target.value})}/><input required placeholder="Lugar" value={form.location} onChange={e=>setForm({...form,location:e.target.value})}/><input placeholder="Descripción" value={form.description} onChange={e=>setForm({...form,description:e.target.value})}/><button>Crear actividad</button></form>}<div className="list">{items.map(x=><article key={x.id}><div><h3>{x.title}</h3><p>{x.location} · {new Date(x.starts_at).toLocaleString('es-CL')}</p><small>{x.description}</small></div>{canEdit&&<button className="danger" onClick={()=>del(x.id)}><Trash2/></button>}</article>)}</div></Page>}

function Documents({canEdit,changed}:{canEdit:boolean;changed:()=>void}){const[items,setItems]=useState<DocumentItem[]>([]),[form,setForm]=useState({title:'',category:'General',url:''});const load=()=>api<DocumentItem[]>('/documents/').then(setItems);useEffect(()=>{void load()},[]);async function add(e:FormEvent){e.preventDefault();await api('/documents/',{method:'POST',body:JSON.stringify(form)});setForm({title:'',category:'General',url:''});load();changed()}async function del(id:number){await api(`/documents/${id}/`,{method:'DELETE'});load();changed()}return <Page title="Centralizar documentos" subtitle="Mantener estatutos, actas y archivos comunitarios disponibles.">{canEdit&&<form className="editor two" onSubmit={add}><input required placeholder="Título" value={form.title} onChange={e=>setForm({...form,title:e.target.value})}/><input placeholder="Categoría" value={form.category} onChange={e=>setForm({...form,category:e.target.value})}/><input placeholder="Enlace al documento (opcional)" value={form.url} onChange={e=>setForm({...form,url:e.target.value})}/><button>Agregar documento</button></form>}<div className="list">{items.map(x=><article key={x.id}><div><h3>{x.title}</h3><p>{x.category}</p>{x.url&&<a href={x.url} target="_blank">Abrir documento</a>}</div>{canEdit&&<button className="danger" onClick={()=>del(x.id)}><Trash2/></button>}</article>)}</div></Page>}

function Indicators({d}:{d:Dashboard|null}){const groups=d?.age_groups||{children:0,adults:0,older:0};const total=Math.max(1,groups.children+groups.adults+groups.older);return <Page title="Comprender el territorio" subtitle="Visualizar información agregada sin exponer datos personales."><section className="metrics"><article><div><strong>{d?.average_age??0}</strong><span>Edad promedio</span></div></article><article><div><strong>{d?.older_adults??0}</strong><span>Personas mayores</span></div></article></section><article className="panel chart"><h3>Distribución por grupo etario</h3>{[['Niños y jóvenes',groups.children],['Adultos',groups.adults],['Personas mayores',groups.older]].map(([l,v])=><div className="bar" key={l as string}><span>{l as string}</span><div><i style={{width:`${(Number(v)/total)*100}%`}}/></div><strong>{v as number}</strong></div>)}</article></Page>}

function Assistant(){const[q,setQ]=useState(''),[answer,setAnswer]=useState('');async function ask(e:FormEvent){e.preventDefault();setAnswer((await api<{answer:string}>('/assistant/',{method:'POST',body:JSON.stringify({question:q})})).answer)}return <Page title="Consultar al asistente" subtitle="Responder preguntas utilizando información comunitaria autorizada."><article className="panel chat"><div className="bot"><Bot/><p>Hola. Puedo ayudarte con publicaciones, actividades y documentos.</p></div>{answer&&<div className="reply">{answer}</div>}<form onSubmit={ask}><input required placeholder="Ejemplo: ¿Cuál es la próxima actividad?" value={q} onChange={e=>setQ(e.target.value)}/><button>Preguntar</button></form></article></Page>}

function Neighbors({changed}:{changed:()=>void}){const[items,setItems]=useState<Profile[]>([]),[msg,setMsg]=useState(''),[form,setForm]=useState({username:'',password:'',first_name:'',last_name:'',email:'',birth_year:'',household_size:'1'});const load=()=>api<Profile[]>('/profiles/').then(setItems);useEffect(()=>{void load()},[]);async function add(e:FormEvent){e.preventDefault();try{await api('/neighbors/register/',{method:'POST',body:JSON.stringify(form)});setMsg('Vecino creado correctamente.');setForm({username:'',password:'',first_name:'',last_name:'',email:'',birth_year:'',household_size:'1'});load();changed()}catch(x){setMsg((x as Error).message)}}return <Page title="Administrar vecinos" subtitle="Crear cuentas y mantener el registro comunitario."><form className="editor two" onSubmit={add}><input required placeholder="Usuario" value={form.username} onChange={e=>setForm({...form,username:e.target.value})}/><input required type="password" placeholder="Contraseña temporal" value={form.password} onChange={e=>setForm({...form,password:e.target.value})}/><input required placeholder="Nombre" value={form.first_name} onChange={e=>setForm({...form,first_name:e.target.value})}/><input placeholder="Apellido" value={form.last_name} onChange={e=>setForm({...form,last_name:e.target.value})}/><input type="email" placeholder="Correo" value={form.email} onChange={e=>setForm({...form,email:e.target.value})}/><input type="number" placeholder="Año de nacimiento" value={form.birth_year} onChange={e=>setForm({...form,birth_year:e.target.value})}/><input type="number" min="1" placeholder="Integrantes del hogar" value={form.household_size} onChange={e=>setForm({...form,household_size:e.target.value})}/><button>Registrar vecino</button>{msg&&<small>{msg}</small>}</form><div className="table"><div className="tr head"><span>Nombre</span><span>Usuario</span><span>Rol</span><span>Hogar</span></div>{items.map(x=><div className="tr" key={x.id}><span>{x.first_name} {x.last_name}</span><span>{x.username}</span><span>{x.role}</span><span>{x.household_size}</span></div>)}</div></Page>}

function Page({title,subtitle,children}:{title:string;subtitle:string;children:React.ReactNode}){return <section className="page"><div className="page-heading"><h2>{title}</h2><p>{subtitle}</p></div>{children}</section>}
function Empty({title,text}:{title:string;text:string}){return <article className="panel empty"><ShieldCheck/><h2>{title}</h2><p>{text}</p></article>}
