# Generated by Django 5.2.5 on 2026-08-29 03:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BoardRole',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=80, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Commune',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120)),
            ],
        ),
        migrations.CreateModel(
            name='Province',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120)),
            ],
        ),
        migrations.CreateModel(
            name='Region',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='NeighborhoodOrganization',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=180)),
                ('rut', models.CharField(max_length=20, unique=True)),
                ('purpose', models.TextField()),
                ('relation_funds', models.CharField(blank=True, max_length=160)),
                ('constitution_date', models.DateField()),
                ('legal_representative', models.CharField(max_length=160)),
                ('institution_type', models.CharField(default='Junta de vecinos', max_length=100)),
                ('thematic_area', models.CharField(default='Desarrollo comunitario', max_length=120)),
                ('legal_personality', models.CharField(blank=True, max_length=80)),
                ('assets', models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ('address', models.CharField(max_length=220)),
                ('commune', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='organizations', to='organizations.commune')),
            ],
        ),
        migrations.AddField(
            model_name='commune',
            name='province',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='communes', to='organizations.province'),
        ),
        migrations.AddField(
            model_name='province',
            name='region',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='provinces', to='organizations.region'),
        ),
        migrations.CreateModel(
            name='BoardMember',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.PositiveIntegerField()),
                ('full_name', models.CharField(max_length=160)),
                ('assigned_at', models.DateField()),
                ('active', models.BooleanField(default=True)),
                ('role', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='organizations.boardrole')),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='board_members', to='organizations.neighborhoodorganization')),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('organization', 'role'), name='unique_active_board_role')],
            },
        ),
        migrations.AddConstraint(
            model_name='commune',
            constraint=models.UniqueConstraint(fields=('province', 'name'), name='unique_commune_province'),
        ),
        migrations.AddConstraint(
            model_name='province',
            constraint=models.UniqueConstraint(fields=('region', 'name'), name='unique_province_region'),
        ),
    ]
